spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: asifali_11
  jpa:
    hibernate:
      ddl-auto: update

#Configuring static user credential
  security:
    user:
      name: asif
      password: asifali_11